### ISSUE TITLE
Actions for a user with interpretation R only are including share, edit and delete

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#16]
From the interpretation wall it seems that the user is able to edit, delete and share. Once you explore, the only actions available are Like and Reply.

**Comment by nancyespinoza** [comment]
![R only actions (explore).PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46dad4952d8e9ae98eeaab4aab53e3d461433f63250bb12e39c7af6aaf50740b0a0c0abe4b4a5a16a8acdd79f2e36e70d80902edd16d5871926945aebf830da313f871d51bdaebe5c01982fa3737e683854e3b1a00118aff5a37a99843cd4abb.PNG)
![R only actions.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46dad4952d8e9ae98eeaab4aab53e3d665043761260ea62864c7b96aea407f040b0d1af913580d11f5f9892ba1b36824de5e0cecc3714d36976345f3e5db55ea43a82a994e82bcbd8f48c5e13e25e089864d3a1b1755.PNG)

**Comment by adrianq** [comment]
@rodmelia @nancyespinoza There is a problem with the approach we discussed yesterday. This is what we said:
- IS OWNER | ALL: like, edit, delete, share, reply
- R/W: like, share, reply
- R: like, reply

The main problem is that 'reply' is not working unless the user has 'write permissions' in the interpretation. It is not working for users with 'read permissions'.

You can test this in the maps application. If you go to maps and access an interpretation with 'read permissions' you will be able to see the 'reply' button. However, when you try to submit a comment you get an error because the backend does not allow to create a new comment if you don't have 'write permissions'. This is obviously a bug in DHIS2 and I have no idea what their plans are in this concern. We can still implement what we discussed yesterday but reply for read-only users will not work because of the backend implementation.

**Comment by rodmelia** [comment]
@adrianq  - Let's raise this as a bug in Jira, but please implement based on the agreed design. That means that while interpretations with RO continue not allowing comments, the comment will not save.

**Comment by tokland** [comment]
Bug created: https://jira.dhis2.org/browse/DHIS2-5760
