### ISSUE TITLE
Link does not open Maps in interpretation mode

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#8]
Maps open with the left panel open and the right panel close.

**Comment by nancyespinoza** [comment]
![Maps Opens LPO-RPC.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46c5958a30c2acb98ae7ac03886ddfd91b7604316546b3397f8fe62bab0021435a0d1af9150a0b11aef9db7eafb63c708d595fb9856f5875d42103eee9dc4be05ce36ade0d97bcae8b44cae93821e4898b4f371a001b80fd4f78.png)

**Comment by adrianq** [comment]
This is a UiO decision. Rodolfo will discuss with them next week

**Comment by rodmelia** [comment]
@adrianq  - while in Oslo, we noticed that the problem is in the URL - you are currently using a capital 'I' for interpretionid - you need to use lower case. As soon as you do that, the right panel will open, preloading the correct interpretation. Yes, left panel stays open.

**Comment by tokland** [comment]
@rodmelia Right. It looks like interpretation-app has always used `interpretationId=VALUE` as param and it worked in analytics apps because its parsing function (AppManager.getUrlParam) is case-insensitive. However, maps-app is case-sensitive. Updated to `interpretationid=VALUE` so it works in analytics and maps apps:

https://github.com/EyeSeeTea/interpretation-app/pull/40
